### ISSUE TITLE
There is no phone document node

### ISSUE THREAD

**Issue by cvetanovskaa** [officeluv/cxml#18]
There are no documents nodes for phone & telephone_number, which results in the phone values being passed as a hash: 

`
<Phone telephone_number=\"{:country_code=&gt;{:iso_country_code=&gt;&quot;US&quot;, :content=&gt;&quot;1&quot;}, :area_or_city_code=&gt;&quot;123&quot;, :number=&gt;&quot;4567890&quot;}
`

They should instead generate a <Phone> cXML node:
`
<Phone name="work">
  <TelephoneNumber>
    <CountryCode isoCountryCode="US">1</CountryCode>
    <AreaOrCityCode>855</AreaOrCityCode>
    <Number>8671234</Number>
  </TelephoneNumber>
</Phone>
`

**Comment by cvetanovskaa** [comment]
I created this PR: https://github.com/officeluv/cxml-ruby/pull/19 to solve this problem. Let me know if you have any thoughts/suggestions :)

**Comment by joshbeckman** [comment]
Released in v0.7.0
